### ISSUE TITLE
Cannot resolve ${_param:ceph_admin_keyring}

### ISSUE THREAD

**Issue by Projoke** [salt-formulas/salt-formula-ceph#6]
```shell
root@cfg01:/srv/salt/reclass# reclass-salt --top
Cannot resolve ${_param:ceph_admin_keyring} in the context of ceph:common:keyring:admin:key
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/reclass/datatypes/parameters.py", line 213, in _interpolate_inner
    new = refvalue.render(self._base)
  File "/usr/lib/python2.7/dist-packages/reclass/utils/refvalue.py", line 110, in render
    return self._assemble(resolver)
  File "/usr/lib/python2.7/dist-packages/reclass/utils/refvalue.py", line 97, in _assemble
    return resolver(self._refs[0])
  File "/usr/lib/python2.7/dist-packages/reclass/utils/refvalue.py", line 109, in <lambda>
    resolver = lambda s: self._resolve(s, context)
  File "/usr/lib/python2.7/dist-packages/reclass/utils/refvalue.py", line 83, in _resolve
    raise UndefinedVariableError(ref)
UndefinedVariableError
```

**Comment by jiribroulik** [comment]
This is old issue with old formula. Has been fixed 3 weeks from now.
